= Introduction

Direct-Sequence spread spectrum (DSSS) modulation is the basis of many modern wireless systems, a famously known example is modern GPS. The idea behind DSSS is simple, a transmitter spreads a single data bit into many chips. Chips are created using a pseudorandom sequence generated from a Linear Feedback Shift Register (LFSR), expanding the single data bit into a much longer sequence, resulting in transmitting over a considerably wider bandwidth than the original single data bit alone would need. A receiver that knows the same chip sequence can despread the signal and recover the original data, while other receivers that do not know the exact code sequence only sees noise and can't descramble the incoming chips. This property gives DSSS systems a decent resistance to interference and also allows different users to share the same frequency band simultaneously. // TODO:  cite any bloody DSSS survey (Pickholtz)

In this Master Project, the goal of the project is building a working DSSS transmitter and receiver in hardware on a DE2 FPGA. A receiver does not know when a transmission starts or what phase of the spreading code it will see first, and must search for the correct code phase before it can track it. Once it found the correct code, it considers it self `synchronized`. Small clock differences between transmitter and receiver mean the receiver must constantly adjust its own code phase to stay locked onto the transmitter. These problems become harder under the constraints of a FPGA system running from a 50 MHz clock and no floating-point hardware.

This project addresses these problems by designing and implementing a complete DSSS communication system in hardware. The project splits the system across three separate FPGA boards. A transmitter which spreads and outputs the individual chips over an ADC add-on board, a channel which injects attenuation and noise, and a receiver that must acquire and track the spreading code.

The whole project is implemented using the SpinalHDL language, a Scala based hardware description language, which compiles into Verilog or VHDL. This project also considers the impacts of SpinalHDL on the whole design and implementation process. It serves as a test of how well SpinalHDLs abstractions hold up on a decently complex design. The receiver is the central focus of this work, since it has to solve both the code acquisition and code tracking problems.

This projects documentation begins with the theoretical background needed to follow the rest of the thesis, covering cross-correlation, the behaviour of signals in noise, and the principles of Direct-Sequence Spread Spectrum. This is followed by a description of the system design and FPGA implementation, starting with a short introduction to SpinalHDL itself, before covering the transmitter, the emulated channel, and the receiver's acquisition and tracking logic in detail. The final chapters present the simualtion of the system, the results and conclude the projects documentation. 

= Theoretical Background

This chapter discusses the theoretical background before moving to the actual implementation of the design on hardware, beginning with `Cross Correlation`.

== Cross Correlation

Cross-correlation quantifies the similarity between two signals as a function of a relative time shift $tau$. For two real, discrete-time sequences $x[n]$ and $y[n]$, the cross-correlation is defined as

$ R_{x y}[k] = sum_{n=-infinity}^{infinity} x[n] med y[n+k] $

When $x = y$, this reduces to the *autocorrelation* $R_{x x}[k]$, which measures how similar a signal is to a time-shifted copy of itself. Autocorrelation matters for DSSS because it is exactly the code's own correlation properties that determine how sharply we can localize the correct code phase during acquisition.

=== Properties relevant to spreading codes

For a pseudorandom noise (PN) sequence $c[n] in {+1,-1}$ of period $N$, two properties matter for this project, the first property is a good spreading code. A good spreading code should have a sharply peaked autocorrelation function, a single high value at zero lag ($k=0$) and low, ideally near-zero, values ("sidelobes") at all other lags:

$ R_{c c}[k] = cases(
  N & "if" k equiv 0 mod N,
  -1 " (or small)" & "otherwise"
) $

This is what makes it possible to identify the correct code phase unambiguously, misalignment collapses the correlation output toward zero, while perfect alignment produces a strong peak. Maximal-length LFSR sequences (m-sequences) of length $N = 2^n - 1$ achieve exactly this two-valued autocorrelation, with off-peak value $-1$. This project relies on that property directly, the spreading code is generated by a 10-bit LFSR, giving a period of $N=1023$ chips (see chapter: System Overview), and every acquisition and tracking correlator in the design depends on that sharp, single peak existing.

The second property is `Cross-correlation` between distinct codes in a multi-user system, low cross-correlation between different users codes is what lets them share the same band with limited mutual interference. This project only ever runs a single transmitter-receiver pair, so this property isn't directly exercised here, but it's the same underlying reason DSSS is used for multi-user systems in general, and it comes back briefly in the near-far discussion at the end of this chapter.

=== The sliding correlator

A receiver does not know the incoming code phase in advance. It computes $R_{r c}[k]$ between the received chip stream $r[n]$ and a locally generated, phase-shifted replica of the code $c[n+k]$, for a range of trial shifts $k$. This is the sliding correlator, band the shift $k$ that maximizes $|R_{r c}[k]|$ is the acquired code phase.

This is exactly what the receiver's acquisition stage does in hardware. As shown in the `System Overview` chapter when describing the acquisition.

== Signals and Noise

=== Channel model

The channel between transmitter and receiver is commonly modeled as an Additive White Gaussian Noise (AWGN) channel:

$ r(t) = s(t) + n(t) $

where $s(t)$ is the transmitted (spread) signal and $n(t)$ is zero-mean Gaussian noise with power spectral density $N_0 slash 2$ (two-sided). "White" means the noise power is uniformly distributed across frequency, so it corrupts every chip independently. This is the idealized model this project's channel board targets As described in Channel Emulation, the FPGA has no floating-point hardware and so instead of true Gaussian noise, the channel sums the outputs of five independent LFSRs and relies on the Central Limit Theorem to approximate a Gaussian-like distribution.

The Central Limit Theorem states that the sum of enough independent random variables tends toward a Gaussian distribution, regardless of how the individual variables themselves are distributed. Each LFSRs own output bit is nowhere near Gaussian on its own, but adding together several roughly-uniform sources pulls the combined result toward a proper bell curve. This is exactly the mechanism the channel board exploits to approximate AWGN.

=== SNR and $E_b slash N_0$

Two related figures of are used throughout this thesis, `SNR`, defined as$P_"signal" slash P_"noise"$, ratio of signal to noise power (often per chip in DSSS).
The other is $E_b slash N_0$, defined as Energy per information bit relative to noise power spectral density, the standard measure for comparing digital modulation schemes independent of bandwidth.

Because DSSS trades bandwidth for robustness, the chip-level SNR seen by the receiver can be considerably worse than the bit-level SNR recovered after despreading. This gap is exactly the processing gain discussed below. The project's Python BER-vs-SNR sweep (`ber_vs_snr.py`) reports results in chip-level SNR, since that's the quantity the channel board's `noise` and `attenuation` settings directly control.

=== Matched filtering and the correlation receiver

For a known pulse shape in AWGN, the linear filter that maximizes the output SNR at the sampling instant is the matched filter, whose impulse response is the time-reversed, conjugated transmit pulse:

$ h(t) = s(T_b - t) $

For rectangular chip/bit pulses, as used here, the matched filter is equivalent to an integrate-and-dump correlator. Meaning, multiplying the received signal by a local replica of the expected waveform and integrating over the symbol period. This part necessart, a matched filter that isn't aligned with its target pulse stops being matched at all.

=== Bit error rate

For binary antipodal signalling (BPSK-equivalent, matching the $plus.minus 1$ chip values used here) in AWGN, the theoretical bit error probability after matched filtering is

$ P_b = Q!(sqrt(2 E_b slash N_0)) $

where $Q(x) = frac(1, sqrt(2 pi)) integral_x^infinity e^{-u^2 slash 2} d u$ is the Gaussian tail function. This closed-form curve is the benchmark the project's simulated BER-vs-SNR results (produced by `ber_vs_snr.py`) are compared against later in this thesis, and is what any measured coding or processing gain of the spreading system is measured relative to. // TODO: use the measured coding gain numbers in from the Results chapter 

== Direct-Sequence Spread Spectrum

=== Spreading operation

A DSSS transmitter multiplies each data bit $b in {+1,-1}$, held constant for one bit period $T_b$, by a PN chip sequence $c[n] in {+1,-1}$ running at a much higher rate:

$ s[n] = b dot c[n], quad n = 0, dots, N_c - 1 $

where $N_c$ chips are transmitted per data bit. In the ${0,1}$ domain, this bipolar multiplication is equivalent to a single XOR.

=== Processing gain

Processing gain describes the ratio of chip rate to bit rate defines the processing gain:

$ G_p = frac(R_c, R_b) = frac(T_b, T_c) = N_c $

expressed in decibels as $G_p ["dB"] = 10 log_10 (N_c)$. For this project's spreading code, $N_c = 1023$ chips per bit, giving $G_p approx 30.1$ dB.

Before spreading, a data bit occupies a bandwidth on the order of $R_b$. Spreading it with $N_c$ chips widens that bandwidth to roughly $R_c = N_c dot R_b$. At the receiver, despreading multiplies the incoming signal by the same code a second time. For the wanted signal, this second multiplication exactly cancels the first, collapsing its bandwidth back down to $R_b$. For noise or interference that is uncorrelated with the code, the same multiplication has the opposite effect, rather than concentrating power into the narrow $R_b$ band, it spreads that power out over roughly $R_c$. A receiver filter matched to the narrow $R_b$ bandwidth then only picks up a fraction $R_b slash R_c = 1 slash G_p$ of that interference power, while the full wanted signal power is recovered. The result is that the signal-to-interference ratio at the output of the despreading correlator is $G_p$ times higher than at its input, this factor-of-$G_p$ improvement is what "processing gain" refers to.

=== Despreading and code synchronization

At the receiver, despreading is the inverse operation. The incoming chip stream is correlated against a locally generated and correctly phase-aligned, replica of the same PN code and integrated over one bit period:

$ hat(b) = "sign"( sum_{n=0}^{N_c-1} r[n] med c[n] ) $

Correct operation depends entirely on the local code being phase-aligned with the incoming code. This code synchronization problem splits into two sub-problems, both implemented directly in this project's receiver:

*Acquisition*: coarse alignment, found via the sliding correlator search described above, declaring synchronization once one candidate offset's correlation clearly stands out from the rest, (see Receiver Implementation).
*Tracking*: fine, continuous alignment maintained after acquisition. Since transmitter and receiver clocks are never perfectly matched, small frequency offsets cause the code phases to slowly drift apart over time. The correlation peak would walk away from the sample instant if left uncorrected. A Delay-Locked Loop (DLL) compares early and late correlator outputs to generate an error signal that adjusts the local code clock, keeping the peak centered.

=== LFSR-generated PN sequences

The chip sequences are generated by Linear Feedback Shift Registers implementing primitive polynomials over $"GF"(2)$. An $n$-bit LFSR with a primitive feedback polynomial produces a maximal-length sequence (m-sequence) with period

$ N = 2^n - 1 $

M-sequences have three properties, the "balance", "run", and "correlation" properties, that make them suitable spreading codes:

The properties can be described as follows:
- Balance: in one period, the number of 1s exceeds the number of 0s by exactly one.
- Run distribution: runs of consecutive equal chips occur with geometrically decreasing frequency, mimicking a random binary sequence.
- Two-valued autocorrelation: as given above, $R_{c c}[k] = N$ at $k=0$ and $-1$ elsewhere — the property directly exploited for acquisition.

This project uses a 10-bit LFSR, giving $N = 1023$ chips per period.


=== Multiple access and the near-far problem

Because distinct users' codes have low mutual cross-correlation, several DSSS transmissions can share the same frequency band simultaneously (Code-Division Multiple Access), with each receiver's correlator suppressing the others as pseudo-noise. If an interfering transmitter's received power is much larger than the desired signals, residual cross-correlation sidelobes can still desturbe the correlation peak, this is called the near-far problem. However, since this project does not implement multiple simultaneous users, we do not describe the theory behind the near-far problem.
