= Outlook

Several parts of this design were built with a working system as the first priority, not resource efficiency or performance. This chapter collects a few ideas and directions for further optimization that based on the choices made in the current implementation, several of which map onto standard GNSS receiver design trade-offs described in the literature @springer_sig_proc.

== ADC bit depth
It is possible to reduce the number of quantization levels of the analog-to-digital converter, down to as little as one or two bits, without a significant loss in correlation performance, while drastically reducing the hardware complexity of the receiver @receiver_loss. \
This matters a lot for our specific implemenatation choice. The integer `n_adc` is used as a parameter through the entire signal path rather than hardcoded. All 32 parallel `Code_Acquisition` correlators, the three tracking correlators (Early, Prompt, Late), and the `DLL`'s input ports sizes are defined as `n_adc + m_lfsr` bits wide. Reducing `n_adc` does not only shrink the ADC itself, it shrinks every accumulator and adder in all 35 correlators at once. \ // TODO: replace with  exact dB figures from @receiver_loss maybe
For the acquisition stage, 32 parallel correlators were chosen as a tradeoff between search time and FPGA logic usage, the logic freed up by a smaller `n_adc` could be reinvested into more parallel search engines instead. This would improve acquisition time without a larger FPGA.

== DLL loop filter design
The current `DLL` increments or decrements `errorReg` by a fixed step (`+|2`/`-1`) each cycle the early or late accumulator dominates. Then, an `advance` or `delay` command is set when `errorReg` crosses a hardcoded threshold of 20. \
Comparing this to a standard approach in GNSS receiver design specifies a DLL loop filter directly in terms of a target noise bandwidth $B_n$, with the filter order and $B_n$ together determining the trade-off between residual tracking-noise jitter and how quickly the loop can respond to genuine code-phase drift @springer_sig_proc. Since code tracking loops are usually implemented with a first-order filter, replacing the current threshold based implementation with a filter parameterized directly by a chosen $B_n$ would make this an adjustable design parameter rather than somewhat empirically-chosen constants.  This would also make the loop's expected steady-state tracking error predictable ahead of time rather than something to be found only through simulation.

== Correlator spacing
The three tracking correlators are formed by delaying the incoming signal by 0, 1, and 2 clock cycles (`inputRegVec`) before correlating each against the tracking-LFSR reference. This means it takes two full chips to figure out if the code has to be shifted forwards or backwards. The reason the current design uses a full 2 chip spacing rather than a sub-chip spacing is based on the same discussion as in the Introduction. Since the implementation does not allow for faster oversampling, one chip corresponds to exactly one ADC sample, so any early/late spacing narrower than a single chip is not implementable in the current architecture. A narrower correlator would either require a higher rate ADC or an internal oversampling clock for the correlator taps specifically, while the LFSR itself continues to advance at the 50 MHz chip rate.
