= System Design
The used FPGA development boards provide a $50 "MHz"$ clock, which is selected as both the system clock rate and the chip rate of the spreading sequence.

The system itself has three main components, which this chapte describes in detail. The transmitter generates and sends out the spread signal, the channel simulates noise and tries to simulate a 'real world scenario', and the receiver acquires and tracks the spreading code to try to rebuild the original data from the transmitter.

== System Overview

The 3 main components of the system, the transmitter, the channel, and the receiver, also correspond to the 3 FPGA boards used, each component having its own FPGA board.
The transmitter begins by sending out data. It spreads a single data bit into 1023 chips. For the receiver to be synchronized, the transmitter and receiver have to use the same spreading code, generated from the same LFSR polynomial. The transmitter then sends out these chips through its onboard 14 bit DAC.
Between the transmitter and receiver lies the channel. It is made to create artificial noise. This allows to simulate a real world environment. The channel is implemented in a way to make it adjustable on the fly. This means it can adjust the attenuation and noise of the signal during system runtime on the FPGA boards.
The receiver is the most complex part of the system. It receives chips either directly from the transmitter or from the channel on its ADC input, and has to try to stay in sync with the transmitter at all times.
Before it can track anything however, the receiver first has to find the transmitters code phase in the first place. This is done by acquisition, where many correlators, each checking a different offset of the LFSR, run in parallel and search for the offset that gives the strongest correlation. Once an offset clearly stands out from the rest, the receiver uses that offset and considers itself synced and begins tracking.

The receiver uses the same polynomial as the transmitter for its own LFSR. To ensure the system stays synced, we always run three different correlators, one for the expected current bit in the LFSR, one for the previous bit, and one for the next bit in time. We compare each correlators results, and if the earlier or later correlator shows a much better result than the current one, we shift the LFSR forward, or step it back.

This allows us to continuously adjust the LFSR index and correct possible synchronization mistakes.

// #figure(
//   image("TODO", width: 80%),
//   caption: [TODO]
// )

== Spreading Sequence Generation

The spreading code used throughout the system is generated by an unrolled LFSR class. This LFSR unrolls the feedback logic to produce a full parallel output every cycle. Having the full parallel output of the LFSR allows for moving the LFSR forward, or backwards.
The main difference to regular LFSRs is that we do not just output the resulting bit of the LFSR, but every output of each 'tap', polynomial, of the LFSR.
The polynomial itself is passed as an array of tap positions. Each entry in the array represents the exponent of a tap in the polynomial, meaning the polynomial of the LFSR is not hardcoded, but adjustable on compile time.
Since we are limited to a 50 MHz clock on both receiver and transmitter, TODO

Used by every software implementation, also common in hardware.

== Code Tracking

Delay-Locked loop

Early, Prompt, and Late correlator
